services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: risk
      POSTGRES_DB: riskcontrol
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_backend
    restart: always
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:risk@db:5432/riskcontrol
    env_file:
      - .env
  nginx:
    build:
      context: .
      dockerfile: Nginx.dockerfile
    container_name: nginx_gateway
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  db_data: {}