#cloud-config
package_update: true
packages:
  - git
runcmd:
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  - usermod -aG docker azureuser
  - curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - su - azureuser -c "git clone https://github.com/apvasquezo/O-risk /home/azureuser/app/backend"
  - su - azureuser -c "cd /home/azureuser/app/backend && /usr/local/bin/docker-compose up -d"
  - su - azureuser -c "git clone https://github.com/apvasquezo/app-risk /home/azureuser/app/frontend"
  - su - azureuser -c "cd /home/azureuser/app/frontend && /usr/local/bin/docker-compose up -d"